# Generated by Django 3.1.7 on 2021-03-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='ongoing',
            field=models.BooleanField(default=True),
        ),
    ]
