# Generated by Django 3.1.7 on 2021-03-26 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='budget',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='description',
            field=models.TextField(default=0.0),
            preserve_default=False,
        ),
    ]
