# Generated by Django 3.1.7 on 2021-03-26 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('website', '0002_campaignapplications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CampaignApplications',
            new_name='CampaignApplication',
        ),
    ]
